server:
  port: ${PORT:8086}

spring:
  application:
    name: notification-service
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info
